name:                sacd-tools
version:             0.1.0.0
github:              "githubuser/sacd-tools"
license:             BSD3
author:              "Jason Hooper"
maintainer:          "nirgle@gmail.com"
copyright:           "2021 Jason Hooper"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cue#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- split

library:
  source-dirs: src

executables:
  sacd-tools-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sacd-tools

tests:
  sacd-tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sacd-tools
